DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(255) NOT NULL CHECK(first != ''),
    last VARCHAR(255) NOT NULL CHECK(last != ''),
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    time_stamp TIMESTAMP NOT NULL DEFAULT NOW()
);